language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest

script:
  - coverage run -m pytest -v tests/test_hello.py
  - coverage report tests/test_hello.py

after_success:
- coveralls