language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest

script:
  - nosetests --with-coverage --cover-package=tests  && coverage report

after_success:
- coveralls